/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#4fdbc8",
        "on-primary": "#003731",
        "primary-container": "#14b8a6",
        "on-primary-container": "#00423b",
        "surface": "#0f131f",
        "surface-dim": "#0f131f",
        "surface-bright": "#353946",
        "surface-container-lowest": "#0a0e1a",
        "surface-container-low": "#171b28",
        "surface-container": "#1b1f2c",
        "surface-container-high": "#262a37",
        "surface-container-highest": "#313442",
        "surface-variant": "#313442",
        "on-surface": "#dfe2f3",
        "on-surface-variant": "#bbcac6",
        "outline": "#859490",
        "outline-variant": "#3c4947",
        "surface-tint": "#4fdbc8",
        "secondary": "#bcc7de",
        "on-secondary": "#263143",
        "secondary-container": "#3e495d",
        "on-secondary-container": "#aeb9d0",
        "tertiary": "#c0c6db",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#006b5f",
        "inverse-surface": "#dfe2f3",
        "inverse-on-surface": "#2c303d",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg":  ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md":  ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "gutter": "24px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
